export const ADEPTLINK_ACCESS_TOKEN = "accessToken";
export const ADEPTLINK_REFRESH_TOKEN = "refreshToken";
export const ADEPTLINK_ROLE = "role";
export const ADEPTLINK_ACCESS_TOKEN_EXPIRED = "accessTokenExpiredIn";
export const ADEPTLINK_USER = "user";
export const RECENTLY_SEARCH_PRODUCT_RESULT = "RECENTLY_SEARCH_PRODUCT_RESULT";
export const RECENTLY_SEARCH_SUPPLIER_RESULT =
  "RECENTLY_SEARCH_SUPPLIER_RESULT";
export const TEMPORARY_CART = "TEMPORARY_CART";
export const SUPPLIER_CONTACT = "SUPPLIER_CONTACT";
export const ORDER = "ORDER";
